//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public int ProvinceRef { get; set; }
        public int CityRef { get; set; }
        public string PostalAddress { get; set; }
        public string PostalCode { get; set; }
        public int UserRef { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
