//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackList
    {
        public int Id { get; set; }
        public Nullable<int> UserRef { get; set; }
        public string Reason { get; set; }
        public int PenaltyRef { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> ForbidenPhraseRef { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> BadContentTypeRef { get; set; }
        public string MACAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string DeviceIMEI { get; set; }
    
        public virtual ForbiddenPhrase ForbiddenPhrase { get; set; }
        public virtual Penalty Penalty { get; set; }
        public virtual User User { get; set; }
    }
}
