//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Offerable = new HashSet<Offerable>();
            this.OfferableTypeBrand = new HashSet<OfferableTypeBrand>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<short> Priority { get; set; }
    
        public virtual ICollection<Offerable> Offerable { get; set; }
        public virtual ICollection<OfferableTypeBrand> OfferableTypeBrand { get; set; }
    }
}
