//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarBrands
    {
        public CarBrands()
        {
            this.CarSeries = new HashSet<CarSeries>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<int> CountryRef { get; set; }
        public string Manufacturer { get; set; }
    
        public virtual ICollection<CarSeries> CarSeries { get; set; }
    }
}
