//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.CouponValidOfferable = new HashSet<CouponValidOfferable>();
            this.CouponValidOfferableType = new HashSet<CouponValidOfferableType>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public double OffAmount { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Status { get; set; }
        public Nullable<short> MaxUse { get; set; }
        public Nullable<short> MaxUsePerCustomer { get; set; }
    
        public virtual ICollection<CouponValidOfferable> CouponValidOfferable { get; set; }
        public virtual ICollection<CouponValidOfferableType> CouponValidOfferableType { get; set; }
    }
}
