//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryMethod
    {
        public DeliveryMethod()
        {
            this.OfferableDeliveryMethod = new HashSet<OfferableDeliveryMethod>();
            this.Order = new HashSet<Order>();
            this.SPDeliveryMethod = new HashSet<SPDeliveryMethod>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public bool IsLocal { get; set; }
        public decimal Cost { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public byte DeliveryTimeFrom { get; set; }
        public Nullable<byte> DeliveryTimeTo { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> FreeIfOrderAbove { get; set; }
    
        public virtual ICollection<OfferableDeliveryMethod> OfferableDeliveryMethod { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<SPDeliveryMethod> SPDeliveryMethod { get; set; }
    }
}
