//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPaymentBank
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string LogoUrl { get; set; }
        public string RedirectUrl { get; set; }
        public string Notes { get; set; }
        public int PaymentMethodRef { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
