//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.OfferableTypeProperty = new HashSet<OfferableTypeProperty>();
            this.OfferableTypePropertyValue = new HashSet<OfferableTypePropertyValue>();
            this.PredefinedListValue = new HashSet<PredefinedListValue>();
        }
    
        public int Id { get; set; }
        public bool IsRequired { get; set; }
        public string Tooltip { get; set; }
        public string ErrorMessage { get; set; }
        public string ValidationExpression { get; set; }
        public string Title { get; set; }
        public int TypeRef { get; set; }
        public Nullable<byte> MinChars { get; set; }
        public string Properties { get; set; }
    
        public virtual FieldType FieldType { get; set; }
        public virtual ICollection<OfferableTypeProperty> OfferableTypeProperty { get; set; }
        public virtual ICollection<OfferableTypePropertyValue> OfferableTypePropertyValue { get; set; }
        public virtual ICollection<PredefinedListValue> PredefinedListValue { get; set; }
    }
}
