//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForbiddenPhrase
    {
        public ForbiddenPhrase()
        {
            this.BlackList = new HashSet<BlackList>();
        }
    
        public int Id { get; set; }
        public string Phrase { get; set; }
        public int PenaltyRef { get; set; }
        public byte Severity { get; set; }
    
        public virtual ICollection<BlackList> BlackList { get; set; }
        public virtual Penalty Penalty { get; set; }
    }
}
