//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grocery
    {
        public int Id { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Code { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<short> ScoresToBuy { get; set; }
        public Nullable<short> ScoreCount { get; set; }
        public string ImageUrl { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<byte> FreshnessGuaranteeDays { get; set; }
    
        public virtual Offerable Offerable { get; set; }
    }
}
