//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferableType
    {
        public OfferableType()
        {
            this.CouponValidOfferableType = new HashSet<CouponValidOfferableType>();
            this.Offerable = new HashSet<Offerable>();
            this.OfferableTypeBrand = new HashSet<OfferableTypeBrand>();
            this.OfferableTypeProperty = new HashSet<OfferableTypeProperty>();
            this.OfferableType1 = new HashSet<OfferableType>();
            this.SearchHistory = new HashSet<SearchHistory>();
            this.SPActivityField = new HashSet<SPActivityField>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> ParentRef { get; set; }
        public string PhotoUrl { get; set; }
        public string Keywords { get; set; }
        public Nullable<short> Priority { get; set; }
        public Nullable<bool> IsVirtual { get; set; }
        public Nullable<double> Rank { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<CouponValidOfferableType> CouponValidOfferableType { get; set; }
        public virtual ICollection<Offerable> Offerable { get; set; }
        public virtual ICollection<OfferableTypeBrand> OfferableTypeBrand { get; set; }
        public virtual ICollection<OfferableTypeProperty> OfferableTypeProperty { get; set; }
        public virtual ICollection<OfferableType> OfferableType1 { get; set; }
        public virtual OfferableType OfferableType2 { get; set; }
        public virtual ICollection<SearchHistory> SearchHistory { get; set; }
        public virtual ICollection<SPActivityField> SPActivityField { get; set; }
    }
}
