//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offerable
    {
        public Offerable()
        {
            this.Comment = new HashSet<Comment>();
            this.CouponValidOfferable = new HashSet<CouponValidOfferable>();
            this.Off = new HashSet<Off>();
            this.OfferableDeliveryMethod = new HashSet<OfferableDeliveryMethod>();
            this.OfferablePicture = new HashSet<OfferablePicture>();
            this.OfferableTypePropertyValue = new HashSet<OfferableTypePropertyValue>();
            this.OfferableVariation = new HashSet<OfferableVariation>();
            this.OrderItem = new HashSet<OrderItem>();
            this.QuantityOff = new HashSet<QuantityOff>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SPRef { get; set; }
        public int TypeRef { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> OperatorUserRef { get; set; }
        public bool IsSpecial { get; set; }
        public Nullable<bool> IsBackOrder { get; set; }
        public Nullable<int> BrandRef { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<CouponValidOfferable> CouponValidOfferable { get; set; }
        public virtual Grocery Grocery { get; set; }
        public virtual ICollection<Off> Off { get; set; }
        public virtual ICollection<OfferableDeliveryMethod> OfferableDeliveryMethod { get; set; }
        public virtual ICollection<OfferablePicture> OfferablePicture { get; set; }
        public virtual OfferableType OfferableType { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OfferableTypePropertyValue> OfferableTypePropertyValue { get; set; }
        public virtual ICollection<OfferableVariation> OfferableVariation { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ICollection<QuantityOff> QuantityOff { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
