//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferableTypePropertyValue
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public int FieldRef { get; set; }
        public int OfferableRef { get; set; }
        public Nullable<int> SelectedPredefinedValueRef { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Offerable Offerable { get; set; }
        public virtual PredefinedListValue PredefinedListValue { get; set; }
    }
}
