//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.BackOrderPartCondition = new HashSet<BackOrderPartCondition>();
        }
    
        public int Id { get; set; }
        public int OrderRef { get; set; }
        public int OfferableRef { get; set; }
        public short Quantity { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<BackOrderPartCondition> BackOrderPartCondition { get; set; }
        public virtual Offerable Offerable { get; set; }
        public virtual Order Order { get; set; }
    }
}
