//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItem = new HashSet<OrderItem>();
            this.TransactionDetail = new HashSet<TransactionDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserRef { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public Nullable<int> SPRef { get; set; }
        public int DeliveryMethodRef { get; set; }
        public int PaymentMethodRef { get; set; }
        public int AddressRef { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual DeliveryMethod DeliveryMethod { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetail { get; set; }
    }
}
