//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.EPaymentBank = new HashSet<EPaymentBank>();
            this.Order = new HashSet<Order>();
            this.SPPaymentMethod = new HashSet<SPPaymentMethod>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<byte> Discount { get; set; }
    
        public virtual ICollection<EPaymentBank> EPaymentBank { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<SPPaymentMethod> SPPaymentMethod { get; set; }
    }
}
