//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.OfferablePicture = new HashSet<OfferablePicture>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public string Alternate { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string ThumbnailUrl { get; set; }
    
        public virtual ICollection<OfferablePicture> OfferablePicture { get; set; }
    }
}
