//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredefinedListValue
    {
        public PredefinedListValue()
        {
            this.OfferableTypePropertyValue = new HashSet<OfferableTypePropertyValue>();
        }
    
        public int Id { get; set; }
        public string Item { get; set; }
        public int FieldRef { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual ICollection<OfferableTypePropertyValue> OfferableTypePropertyValue { get; set; }
    }
}
