//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnBack
    {
        public ReturnBack()
        {
            this.ReturnBackResult = new HashSet<ReturnBackResult>();
        }
    
        public int Id { get; set; }
        public int OfferableRef { get; set; }
        public int UserRef { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
        public decimal Culprit { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<ReturnBackResult> ReturnBackResult { get; set; }
    }
}
