//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Off = new HashSet<Off>();
            this.QuantityOff = new HashSet<QuantityOff>();
            this.UserRole = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Off> Off { get; set; }
        public virtual ICollection<QuantityOff> QuantityOff { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
