//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleTerm
    {
        public int Id { get; set; }
        public int SPRef { get; set; }
        public int OfferableRef { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string ApplicableFor { get; set; }
        public Nullable<int> TermRef { get; set; }
        public Nullable<short> MaxQuantityPerBuyer { get; set; }
        public short Quantity { get; set; }
        public int OperatorUserRef { get; set; }
    }
}
