//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHistory
    {
        public int Id { get; set; }
        public string Criteria { get; set; }
        public Nullable<int> UserRef { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int OfferableTypeRef { get; set; }
        public int ProvinceRef { get; set; }
        public Nullable<int> CarSerieYearRef { get; set; }
        public Nullable<int> CityRef { get; set; }
    
        public virtual City City { get; set; }
        public virtual OfferableType OfferableType { get; set; }
        public virtual Province Province { get; set; }
        public virtual User User { get; set; }
    }
}
