//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public int Id { get; set; }
        public int SearchRef { get; set; }
        public Nullable<int> OfferableRef { get; set; }
        public Nullable<int> SPRef { get; set; }
        public bool IsClicked { get; set; }
        public Nullable<short> Priority { get; set; }
    }
}
