//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public ServiceProvider()
        {
            this.Comment = new HashSet<Comment>();
            this.Offerable = new HashSet<Offerable>();
            this.Order = new HashSet<Order>();
            this.SPActivityField = new HashSet<SPActivityField>();
            this.SPDeliveryMethod = new HashSet<SPDeliveryMethod>();
            this.SPPaymentMethod = new HashSet<SPPaymentMethod>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public int ProvinceRef { get; set; }
        public int CityRef { get; set; }
        public string Address { get; set; }
        public int TypeRef { get; set; }
        public string Logo { get; set; }
        public string Status { get; set; }
        public string PostalCode { get; set; }
        public string WebSite { get; set; }
        public Nullable<short> Reputation { get; set; }
        public string WorkHours { get; set; }
        public Nullable<short> AdminGrantedReputation { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Offerable> Offerable { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<SPActivityField> SPActivityField { get; set; }
        public virtual ICollection<SPDeliveryMethod> SPDeliveryMethod { get; set; }
        public virtual ICollection<SPPaymentMethod> SPPaymentMethod { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
