//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPActivityField
    {
        public int Id { get; set; }
        public int SPRef { get; set; }
        public int CarSerieYearRef { get; set; }
        public int OfferableTypeRef { get; set; }
        public int OfferableCategoryRef { get; set; }
        public int VehicleTypeRef { get; set; }
    
        public virtual OfferableCategories OfferableCategories { get; set; }
        public virtual OfferableCategories OfferableCategories1 { get; set; }
        public virtual OfferableType OfferableType { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
    }
}
