//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int Id { get; set; }
        public int TransactionRef { get; set; }
        public Nullable<int> OrderRef { get; set; }
        public Nullable<int> ReturnbackResultRef { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ReturnBackResult ReturnBackResult { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
