//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.TransactionDetail = new HashSet<TransactionDetail>();
        }
    
        public int Id { get; set; }
        public int BankAccountRef { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string Status { get; set; }
        public string Regarding { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetail { get; set; }
    }
}
